/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodePublicRouteImport } from './routes/$countryCode/_public'
import { Route as CountryCodeProtectedRouteImport } from './routes/$countryCode/_protected'
import { Route as CountryCodePublicIndexRouteImport } from './routes/$countryCode/_public/index'
import { Route as CountryCodePublicStoreRouteImport } from './routes/$countryCode/_public/store'
import { Route as CountryCodePublicCheckoutRouteImport } from './routes/$countryCode/_public/checkout'
import { Route as CountryCodePublicCartRouteImport } from './routes/$countryCode/_public/cart'
import { Route as CountryCodeProtectedSettingsRouteImport } from './routes/$countryCode/_protected/settings'
import { Route as CountryCodeProtectedQuotesRouteImport } from './routes/$countryCode/_protected/quotes'
import { Route as CountryCodeProtectedOrdersRouteImport } from './routes/$countryCode/_protected/orders'
import { Route as CountryCodeProtectedEmployeesRouteImport } from './routes/$countryCode/_protected/employees'
import { Route as CountryCodeProtectedDashboardRouteImport } from './routes/$countryCode/_protected/dashboard'
import { Route as CountryCodePublicProductsHandleRouteImport } from './routes/$countryCode/_public/products/$handle'
import { Route as CountryCodePublicCategoriesHandleRouteImport } from './routes/$countryCode/_public/categories/$handle'
import { Route as CountryCodePublicAccountRegisterRouteImport } from './routes/$countryCode/_public/account/register'
import { Route as CountryCodePublicAccountLoginRouteImport } from './routes/$countryCode/_public/account/login'
import { Route as CountryCodePublicAccountAcceptInviteRouteImport } from './routes/$countryCode/_public/account/accept-invite'
import { Route as CountryCodePublicOrderOrderIdPaymentRouteImport } from './routes/$countryCode/_public/order/$orderId/payment'
import { Route as CountryCodePublicOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/_public/order/$orderId/confirmed'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodePublicRoute = CountryCodePublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeProtectedRoute = CountryCodeProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodePublicIndexRoute = CountryCodePublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodePublicRoute,
} as any)
const CountryCodePublicStoreRoute = CountryCodePublicStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodePublicRoute,
} as any)
const CountryCodePublicCheckoutRoute =
  CountryCodePublicCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => CountryCodePublicRoute,
  } as any)
const CountryCodePublicCartRoute = CountryCodePublicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodePublicRoute,
} as any)
const CountryCodeProtectedSettingsRoute =
  CountryCodeProtectedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => CountryCodeProtectedRoute,
  } as any)
const CountryCodeProtectedQuotesRoute =
  CountryCodeProtectedQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => CountryCodeProtectedRoute,
  } as any)
const CountryCodeProtectedOrdersRoute =
  CountryCodeProtectedOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => CountryCodeProtectedRoute,
  } as any)
const CountryCodeProtectedEmployeesRoute =
  CountryCodeProtectedEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => CountryCodeProtectedRoute,
  } as any)
const CountryCodeProtectedDashboardRoute =
  CountryCodeProtectedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => CountryCodeProtectedRoute,
  } as any)
const CountryCodePublicProductsHandleRoute =
  CountryCodePublicProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodePublicRoute,
  } as any)
const CountryCodePublicCategoriesHandleRoute =
  CountryCodePublicCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodePublicRoute,
  } as any)
const CountryCodePublicAccountRegisterRoute =
  CountryCodePublicAccountRegisterRouteImport.update({
    id: '/account/register',
    path: '/account/register',
    getParentRoute: () => CountryCodePublicRoute,
  } as any)
const CountryCodePublicAccountLoginRoute =
  CountryCodePublicAccountLoginRouteImport.update({
    id: '/account/login',
    path: '/account/login',
    getParentRoute: () => CountryCodePublicRoute,
  } as any)
const CountryCodePublicAccountAcceptInviteRoute =
  CountryCodePublicAccountAcceptInviteRouteImport.update({
    id: '/account/accept-invite',
    path: '/account/accept-invite',
    getParentRoute: () => CountryCodePublicRoute,
  } as any)
const CountryCodePublicOrderOrderIdPaymentRoute =
  CountryCodePublicOrderOrderIdPaymentRouteImport.update({
    id: '/order/$orderId/payment',
    path: '/order/$orderId/payment',
    getParentRoute: () => CountryCodePublicRoute,
  } as any)
const CountryCodePublicOrderOrderIdConfirmedRoute =
  CountryCodePublicOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodePublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodePublicRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/dashboard': typeof CountryCodeProtectedDashboardRoute
  '/$countryCode/employees': typeof CountryCodeProtectedEmployeesRoute
  '/$countryCode/orders': typeof CountryCodeProtectedOrdersRoute
  '/$countryCode/quotes': typeof CountryCodeProtectedQuotesRoute
  '/$countryCode/settings': typeof CountryCodeProtectedSettingsRoute
  '/$countryCode/cart': typeof CountryCodePublicCartRoute
  '/$countryCode/checkout': typeof CountryCodePublicCheckoutRoute
  '/$countryCode/store': typeof CountryCodePublicStoreRoute
  '/$countryCode/': typeof CountryCodePublicIndexRoute
  '/$countryCode/account/accept-invite': typeof CountryCodePublicAccountAcceptInviteRoute
  '/$countryCode/account/login': typeof CountryCodePublicAccountLoginRoute
  '/$countryCode/account/register': typeof CountryCodePublicAccountRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodePublicCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodePublicProductsHandleRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodePublicOrderOrderIdConfirmedRoute
  '/$countryCode/order/$orderId/payment': typeof CountryCodePublicOrderOrderIdPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodePublicIndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/dashboard': typeof CountryCodeProtectedDashboardRoute
  '/$countryCode/employees': typeof CountryCodeProtectedEmployeesRoute
  '/$countryCode/orders': typeof CountryCodeProtectedOrdersRoute
  '/$countryCode/quotes': typeof CountryCodeProtectedQuotesRoute
  '/$countryCode/settings': typeof CountryCodeProtectedSettingsRoute
  '/$countryCode/cart': typeof CountryCodePublicCartRoute
  '/$countryCode/checkout': typeof CountryCodePublicCheckoutRoute
  '/$countryCode/store': typeof CountryCodePublicStoreRoute
  '/$countryCode/account/accept-invite': typeof CountryCodePublicAccountAcceptInviteRoute
  '/$countryCode/account/login': typeof CountryCodePublicAccountLoginRoute
  '/$countryCode/account/register': typeof CountryCodePublicAccountRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodePublicCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodePublicProductsHandleRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodePublicOrderOrderIdConfirmedRoute
  '/$countryCode/order/$orderId/payment': typeof CountryCodePublicOrderOrderIdPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/_protected': typeof CountryCodeProtectedRouteWithChildren
  '/$countryCode/_public': typeof CountryCodePublicRouteWithChildren
  '/$countryCode/_protected/dashboard': typeof CountryCodeProtectedDashboardRoute
  '/$countryCode/_protected/employees': typeof CountryCodeProtectedEmployeesRoute
  '/$countryCode/_protected/orders': typeof CountryCodeProtectedOrdersRoute
  '/$countryCode/_protected/quotes': typeof CountryCodeProtectedQuotesRoute
  '/$countryCode/_protected/settings': typeof CountryCodeProtectedSettingsRoute
  '/$countryCode/_public/cart': typeof CountryCodePublicCartRoute
  '/$countryCode/_public/checkout': typeof CountryCodePublicCheckoutRoute
  '/$countryCode/_public/store': typeof CountryCodePublicStoreRoute
  '/$countryCode/_public/': typeof CountryCodePublicIndexRoute
  '/$countryCode/_public/account/accept-invite': typeof CountryCodePublicAccountAcceptInviteRoute
  '/$countryCode/_public/account/login': typeof CountryCodePublicAccountLoginRoute
  '/$countryCode/_public/account/register': typeof CountryCodePublicAccountRegisterRoute
  '/$countryCode/_public/categories/$handle': typeof CountryCodePublicCategoriesHandleRoute
  '/$countryCode/_public/products/$handle': typeof CountryCodePublicProductsHandleRoute
  '/$countryCode/_public/order/$orderId/confirmed': typeof CountryCodePublicOrderOrderIdConfirmedRoute
  '/$countryCode/_public/order/$orderId/payment': typeof CountryCodePublicOrderOrderIdPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/dashboard'
    | '/$countryCode/employees'
    | '/$countryCode/orders'
    | '/$countryCode/quotes'
    | '/$countryCode/settings'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/$countryCode/'
    | '/$countryCode/account/accept-invite'
    | '/$countryCode/account/login'
    | '/$countryCode/account/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/order/$orderId/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/dashboard'
    | '/$countryCode/employees'
    | '/$countryCode/orders'
    | '/$countryCode/quotes'
    | '/$countryCode/settings'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/$countryCode/account/accept-invite'
    | '/$countryCode/account/login'
    | '/$countryCode/account/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/order/$orderId/payment'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/_protected'
    | '/$countryCode/_public'
    | '/$countryCode/_protected/dashboard'
    | '/$countryCode/_protected/employees'
    | '/$countryCode/_protected/orders'
    | '/$countryCode/_protected/quotes'
    | '/$countryCode/_protected/settings'
    | '/$countryCode/_public/cart'
    | '/$countryCode/_public/checkout'
    | '/$countryCode/_public/store'
    | '/$countryCode/_public/'
    | '/$countryCode/_public/account/accept-invite'
    | '/$countryCode/_public/account/login'
    | '/$countryCode/_public/account/register'
    | '/$countryCode/_public/categories/$handle'
    | '/$countryCode/_public/products/$handle'
    | '/$countryCode/_public/order/$orderId/confirmed'
    | '/$countryCode/_public/order/$orderId/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HealthRoute: typeof HealthRoute
  StoreRoute: typeof StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/_public': {
      id: '/$countryCode/_public'
      path: ''
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodePublicRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/_protected': {
      id: '/$countryCode/_protected'
      path: ''
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeProtectedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/_public/': {
      id: '/$countryCode/_public/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodePublicIndexRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/store': {
      id: '/$countryCode/_public/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodePublicStoreRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/checkout': {
      id: '/$countryCode/_public/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodePublicCheckoutRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/cart': {
      id: '/$countryCode/_public/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodePublicCartRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_protected/settings': {
      id: '/$countryCode/_protected/settings'
      path: '/settings'
      fullPath: '/$countryCode/settings'
      preLoaderRoute: typeof CountryCodeProtectedSettingsRouteImport
      parentRoute: typeof CountryCodeProtectedRoute
    }
    '/$countryCode/_protected/quotes': {
      id: '/$countryCode/_protected/quotes'
      path: '/quotes'
      fullPath: '/$countryCode/quotes'
      preLoaderRoute: typeof CountryCodeProtectedQuotesRouteImport
      parentRoute: typeof CountryCodeProtectedRoute
    }
    '/$countryCode/_protected/orders': {
      id: '/$countryCode/_protected/orders'
      path: '/orders'
      fullPath: '/$countryCode/orders'
      preLoaderRoute: typeof CountryCodeProtectedOrdersRouteImport
      parentRoute: typeof CountryCodeProtectedRoute
    }
    '/$countryCode/_protected/employees': {
      id: '/$countryCode/_protected/employees'
      path: '/employees'
      fullPath: '/$countryCode/employees'
      preLoaderRoute: typeof CountryCodeProtectedEmployeesRouteImport
      parentRoute: typeof CountryCodeProtectedRoute
    }
    '/$countryCode/_protected/dashboard': {
      id: '/$countryCode/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/$countryCode/dashboard'
      preLoaderRoute: typeof CountryCodeProtectedDashboardRouteImport
      parentRoute: typeof CountryCodeProtectedRoute
    }
    '/$countryCode/_public/products/$handle': {
      id: '/$countryCode/_public/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodePublicProductsHandleRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/categories/$handle': {
      id: '/$countryCode/_public/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodePublicCategoriesHandleRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/account/register': {
      id: '/$countryCode/_public/account/register'
      path: '/account/register'
      fullPath: '/$countryCode/account/register'
      preLoaderRoute: typeof CountryCodePublicAccountRegisterRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/account/login': {
      id: '/$countryCode/_public/account/login'
      path: '/account/login'
      fullPath: '/$countryCode/account/login'
      preLoaderRoute: typeof CountryCodePublicAccountLoginRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/account/accept-invite': {
      id: '/$countryCode/_public/account/accept-invite'
      path: '/account/accept-invite'
      fullPath: '/$countryCode/account/accept-invite'
      preLoaderRoute: typeof CountryCodePublicAccountAcceptInviteRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/order/$orderId/payment': {
      id: '/$countryCode/_public/order/$orderId/payment'
      path: '/order/$orderId/payment'
      fullPath: '/$countryCode/order/$orderId/payment'
      preLoaderRoute: typeof CountryCodePublicOrderOrderIdPaymentRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
    '/$countryCode/_public/order/$orderId/confirmed': {
      id: '/$countryCode/_public/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodePublicOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodePublicRoute
    }
  }
}

interface CountryCodeProtectedRouteChildren {
  CountryCodeProtectedDashboardRoute: typeof CountryCodeProtectedDashboardRoute
  CountryCodeProtectedEmployeesRoute: typeof CountryCodeProtectedEmployeesRoute
  CountryCodeProtectedOrdersRoute: typeof CountryCodeProtectedOrdersRoute
  CountryCodeProtectedQuotesRoute: typeof CountryCodeProtectedQuotesRoute
  CountryCodeProtectedSettingsRoute: typeof CountryCodeProtectedSettingsRoute
}

const CountryCodeProtectedRouteChildren: CountryCodeProtectedRouteChildren = {
  CountryCodeProtectedDashboardRoute: CountryCodeProtectedDashboardRoute,
  CountryCodeProtectedEmployeesRoute: CountryCodeProtectedEmployeesRoute,
  CountryCodeProtectedOrdersRoute: CountryCodeProtectedOrdersRoute,
  CountryCodeProtectedQuotesRoute: CountryCodeProtectedQuotesRoute,
  CountryCodeProtectedSettingsRoute: CountryCodeProtectedSettingsRoute,
}

const CountryCodeProtectedRouteWithChildren =
  CountryCodeProtectedRoute._addFileChildren(CountryCodeProtectedRouteChildren)

interface CountryCodePublicRouteChildren {
  CountryCodePublicCartRoute: typeof CountryCodePublicCartRoute
  CountryCodePublicCheckoutRoute: typeof CountryCodePublicCheckoutRoute
  CountryCodePublicStoreRoute: typeof CountryCodePublicStoreRoute
  CountryCodePublicIndexRoute: typeof CountryCodePublicIndexRoute
  CountryCodePublicAccountAcceptInviteRoute: typeof CountryCodePublicAccountAcceptInviteRoute
  CountryCodePublicAccountLoginRoute: typeof CountryCodePublicAccountLoginRoute
  CountryCodePublicAccountRegisterRoute: typeof CountryCodePublicAccountRegisterRoute
  CountryCodePublicCategoriesHandleRoute: typeof CountryCodePublicCategoriesHandleRoute
  CountryCodePublicProductsHandleRoute: typeof CountryCodePublicProductsHandleRoute
  CountryCodePublicOrderOrderIdConfirmedRoute: typeof CountryCodePublicOrderOrderIdConfirmedRoute
  CountryCodePublicOrderOrderIdPaymentRoute: typeof CountryCodePublicOrderOrderIdPaymentRoute
}

const CountryCodePublicRouteChildren: CountryCodePublicRouteChildren = {
  CountryCodePublicCartRoute: CountryCodePublicCartRoute,
  CountryCodePublicCheckoutRoute: CountryCodePublicCheckoutRoute,
  CountryCodePublicStoreRoute: CountryCodePublicStoreRoute,
  CountryCodePublicIndexRoute: CountryCodePublicIndexRoute,
  CountryCodePublicAccountAcceptInviteRoute:
    CountryCodePublicAccountAcceptInviteRoute,
  CountryCodePublicAccountLoginRoute: CountryCodePublicAccountLoginRoute,
  CountryCodePublicAccountRegisterRoute: CountryCodePublicAccountRegisterRoute,
  CountryCodePublicCategoriesHandleRoute:
    CountryCodePublicCategoriesHandleRoute,
  CountryCodePublicProductsHandleRoute: CountryCodePublicProductsHandleRoute,
  CountryCodePublicOrderOrderIdConfirmedRoute:
    CountryCodePublicOrderOrderIdConfirmedRoute,
  CountryCodePublicOrderOrderIdPaymentRoute:
    CountryCodePublicOrderOrderIdPaymentRoute,
}

const CountryCodePublicRouteWithChildren =
  CountryCodePublicRoute._addFileChildren(CountryCodePublicRouteChildren)

interface CountryCodeRouteChildren {
  CountryCodeProtectedRoute: typeof CountryCodeProtectedRouteWithChildren
  CountryCodePublicRoute: typeof CountryCodePublicRouteWithChildren
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeProtectedRoute: CountryCodeProtectedRouteWithChildren,
  CountryCodePublicRoute: CountryCodePublicRouteWithChildren,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HealthRoute: HealthRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
